In [ ]:
!pip install opendatasets
!pip install pandas

import nltk
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split


nltk.download('averaged_perceptron_tagger')
nltk.download("wordnet")
nltk.download('punkt')
nltk.download('maxent_treebank_pos_tagger')

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting opendatasets
  Downloading opendatasets-0.1.22-py3-none-any.whl (15 kB)
Requirement already satisfied: kaggle in /usr/local/lib/python3.9/dist-packages (from opendatasets) (1.5.13)
Requirement already satisfied: tqdm in /usr/local/lib/python3.9/dist-packages (from opendatasets) (4.65.0)
Requirement already satisfied: click in /usr/local/lib/python3.9/dist-packages (from opendatasets) (8.1.3)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.9/dist-packages (from kaggle->opendatasets) (8.0.1)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.9/dist-packages (from kaggle->opendatasets) (1.26.15)
Requirement already satisfied: certifi in /usr/local/lib/python3.9/dist-packages (from kaggle->opendatasets) (2022.12.7)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.9/dist-packages (from kaggle->opendatasets) (2.8.2)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.9/dist-packages (from kaggle->opendatasets) (1.16.0)
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from kaggle->opendatasets) (2.27.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.9/dist-packages (from python-slugify->kaggle->opendatasets) (1.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests->kaggle->opendatasets) (3.4)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/dist-packages (from requests->kaggle->opendatasets) (2.0.12)
Installing collected packages: opendatasets
Successfully installed opendatasets-0.1.22
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.9/dist-packages (1.4.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas) (2022.7.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.9/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.9/dist-packages (from pandas) (1.22.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package maxent_treebank_pos_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/maxent_treebank_pos_tagger.zip.

True

In [ ]:
!wget -nc https://storage.googleapis.com/dataset-uploader/bbc/bbc-text.csv
# !gsutil cp gs://dataset-uploader/bbc/bbc-text.csv

--2023-03-31 06:58:37--  https://storage.googleapis.com/dataset-uploader/bbc/bbc-text.csv
Resolving storage.googleapis.com (storage.googleapis.com)... 108.177.121.128, 108.177.120.128, 142.250.159.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|108.177.121.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5057493 (4.8M) [text/csv]
Saving to: ‘bbc-text.csv’

bbc-text.csv        100%[===================>]   4.82M  --.-KB/s    in 0.03s

2023-03-31 06:58:38 (183 MB/s) - ‘bbc-text.csv’ saved [5057493/5057493]

In [ ]:

#code to convert a single sentence  or a array to a vector after finding unique values

from sklearn.feature_extraction.text import CountVectorizer
text ={ "The quick brown fox jumped  over the lazy dog." ,"The brown dog is really the imposter"}
vect=CountVectorizer(analyzer='word',stop_words='english')
vect.fit(text)
print(vect.vocabulary_)
mv=vect.transform(text)
print(mv.shape)
print(mv.toarray())
df=pd.DataFrame(data=(mv.toarray()),index = text ,columns = (vect.get_feature_names_out()))
df

{'brown': 0, 'dog': 1, 'really': 7, 'imposter': 3, 'quick': 6, 'fox': 2, 'jumped': 4, 'lazy': 5}
(2, 8)
[[1 1 0 1 0 0 0 1]
 [1 1 1 0 1 1 1 0]]

,brown,dog,fox,imposter,jumped,lazy,quick,really
The brown dog is really the imposter,1,1,0,1,0,0,0,1
The quick brown fox jumped over the lazy dog.,1,1,1,0,1,1,1,0

In [ ]:

#code to covert text docs into vectors after applying normalization techniques using TFIDF instead of countvectorizer

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
text ={ "The quick brown fox jumped over the lazy dog." ,"The brown dog is  really the imposter "}
vect=TfidfVectorizer(analyzer='word',stop_words='english')
X=vect.fit_transform(text)
print(vect.get_feature_names_out())
df=pd.DataFrame(data=(X.toarray()),index = text ,columns = (vect.get_feature_names_out()))
df

['brown' 'dog' 'fox' 'imposter' 'jumped' 'lazy' 'quick' 'really']

,brown,dog,fox,imposter,jumped,lazy,quick,really
The brown dog is really the imposter,0.409937,0.409937,0.000000,0.576152,0.000000,0.000000,0.000000,0.576152
The quick brown fox jumped over the lazy dog.,0.317800,0.317800,0.446656,0.000000,0.446656,0.446656,0.446656,0.000000

In [ ]:
import nltk
nltk.download("wordnet")

from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
lem=WordNetLemmatizer()
lem.lemmatize('being',pos='n')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

'being'

RUN FROM HERE
**bold text** **bold text**

In [ ]:
#code to POS tag
import nltk

from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import word_tokenize
from nltk import pos_tag


#download average percetion tagged and wordnet is running first time

text ={ "The quick brown fox jumped over the lazy dog." ,"The brown dog is  really  being  the imposter "}

def treebankTag(text):
    words = nltk.word_tokenize(text)
    treebankTagger = nltk.data.load('taggers/maxent_treebank_pos_tagger/english.pickle')
    return treebankTagger.tag(words)

def get_wordnet_pos(treebank_tag):

  if treebank_tag.startswith('J'):
      return wordnet.ADJ
  elif treebank_tag.startswith('V'):
      return wordnet.VERB
  elif treebank_tag.startswith('N'):
      return wordnet.NOUN
  elif treebank_tag.startswith('R'):
      return wordnet.ADV
  elif treebank_tag.startswith('S'):
      return wordnet.ADJ_SAT
  else:
      return  wordnet.NOUN                                                              #as default is noun

# class Lemmatokenizer():
#   def __init__(self):
#     self.wnl = WordNetLemmatizer                                                                #this stuff was testing ways to lemmatize
#   def __call__(self,doc):
#     tokens=word_tokenize(doc)
#     wordsxtags =  nltk.pos_tag(tokens)

#     for word, tag in wordsxtags:
#      return[self.wnl.lemmatize(word=word,pos=get_wordnet_pos(tag)) ]

wnl = WordNetLemmatizer()
lemmas= [' '.join(word) for word in  [[wnl.lemmatize(word=word,pos=get_wordnet_pos((treebankTag(word))[0][1])) for word in l.split()] for l in text]]           #this one worked
# print(lemmas)

# for l in text:
#   for word in l.split():
#       g=(treebankTag(word))[0][1]                                                                                                 #debug code
#       K=get_wordnet_pos(g)
#       print(word,g,K)
#  K
#  L=[get_wordnet_pos((nltk.pos_tag(word)).keys())]

#L=get_wordnet_pos(K)
# L
#   tagged=nltk.pos_tag(text)
#   lem.lemmatize(word,pos=get_wordnet_pos(tag))
# # vect=TfidfVectorizer(analyzer='word',stop_words='english')
# # fit=vect.fit_transform(text)
# # X=vect.get_feature_names_out()
# # #pos tagging
# # tagged=nltk.pos_tag(text)
# # tagged
# #lemmas
# # lem=WordNetLemmatizer()
# # lemmas=[]
# # for word , tag in tagged:
# #   lemmas.append(lem.lemmatize(word,pos=get_wordnet_pos(tag)))

In [ ]:
#vectorizing finally using tfidf
vect=TfidfVectorizer()
fit_text=vect.fit_transform(lemmas)
df=pd.DataFrame(data=(fit_text.toarray()),index=text,columns = (vect.get_feature_names_out()))
df

,be,brown,dog,fox,imposter,jump,lazy,over,quick,really,the
The brown dog is really being the imposter,0.665283,0.236677,0.236677,0.000000,0.332642,0.000000,0.000000,0.000000,0.000000,0.332642,0.473355
The quick brown fox jumped over the lazy dog.,0.000000,0.250969,0.250969,0.352728,0.000000,0.352728,0.352728,0.352728,0.352728,0.000000,0.501938

In [ ]:
#vectorzing using countvectorzation
vect=CountVectorizer(stop_words='english')
fit_text=vect.fit_transform(lemmas)
df=pd.DataFrame(data=(fit_text.toarray()),index=text,columns = (vect.get_feature_names_out()))
df

,brown,dog,fox,imposter,jump,lazy,quick,really
The brown dog is really being the imposter,1,1,0,1,0,0,0,1
The quick brown fox jumped over the lazy dog.,1,1,1,0,1,1,1,0

In [ ]:

import opendatasets as od
import pandas as pd
# od.download("https://www.kaggle.com/datasets/saurabhshahane/ecommerce-text-classification?resource=download")
# file =('/content/ecommerce-text-classification/ecommerceDataset.csv')
df = pd.read_csv('/content/bbc-text.csv')
df.head()

        category                                               text
0           tech  tv future in the hands of viewers with home th...
1       business  worldcom boss  left books alone  former worldc...
2          sport  tigers wary of farrell  gamble  leicester say ...
3          sport  yeading face newcastle in fa cup premiership s...
4  entertainment  ocean s twelve raids box office ocean s twelve...

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['category']=le.fit_transform(df['category'])

df2=df
df2

      category                                               text
0            4  tv future in the hands of viewers with home th...
1            0  worldcom boss  left books alone  former worldc...
2            3  tigers wary of farrell  gamble  leicester say ...
3            3  yeading face newcastle in fa cup premiership s...
4            1  ocean s twelve raids box office ocean s twelve...
...        ...                                                ...
2220         0  cars pull down us retail figures us retail sal...
2221         2  kilroy unveils immigration policy ex-chatshow ...
2222         1  rem announce new glasgow concert us band rem h...
2223         2  how political squabbles snowball it s become c...
2224         3  souness delight at euro progress boss graeme s...

[2225 rows x 2 columns]

ONE HOT ENCODED THE Y COLOUM , EH OKAYISH PERFORMANCE

In [ ]:

df2 = pd.get_dummies(df, columns = ['category'])
# print(df2)

# df2.rename(columns = {'Paper Plane Design Framed Wall Hanging Motivational Office Decor Art Prints (8.7 X 8.7 inch) - Set of 4 Painting made up in synthetic frame with uv textured print which gives multi effects and attracts towards it. This is an special series of paintings which makes your wall very beautiful and gives a royal touch. This painting is ready to hang, you would be proud to possess this unique painting that is a niche apart. We use only the most modern and efficient printing technology on our prints, with only the and inks and precision epson, roland and hp printers. This innovative hd printing technique results in durable and spectacular looking prints of the highest that last a lifetime. We print solely with top-notch 100% inks, to achieve brilliant and true colours. Due to their high level of uv resistance, our prints retain their beautiful colours for many years. Add colour and style to your living space with this digitally printed painting. Some are for pleasure and some for eternal bliss.so bring home this elegant print that is lushed with rich colors that makes it nothing but sheer elegance to be to your friends and family.it would be treasured forever by whoever your lucky recipient is. Liven up your place with these intriguing paintings that are high definition hd graphic digital prints for home, office or any room.':'Description'}, inplace = True)
df2.head()

In [ ]:
text= df2['text'][:]
text

In [ ]:
#this one takes time at around 10 minutes to 15minutes - for around 2000 rows
def treebankTag(text):
    words = nltk.word_tokenize(text)
    treebankTagger = nltk.data.load('taggers/maxent_treebank_pos_tagger/english.pickle')
    return treebankTagger.tag(words)

def get_wordnet_pos(treebank_tag):

  if treebank_tag.startswith('J'):
      return wordnet.ADJ
  elif treebank_tag.startswith('V'):
      return wordnet.VERB
  elif treebank_tag.startswith('N'):
      return wordnet.NOUN
  elif treebank_tag.startswith('R'):
      return wordnet.ADV
  elif treebank_tag.startswith('S'):
      return wordnet.ADJ_SAT
  else:
      return  wordnet.NOUN

wnl = WordNetLemmatizer()
lemmas= [' '.join(word) for word in  [[wnl.lemmatize(word=word,pos=get_wordnet_pos((treebankTag(word))[0][1])) for word in l.split()] for l in text]]

In [ ]:
#model stuff
import pandas as pd
from sklearn.model_selection import train_test_split
X_label=lemmas
y_label=df2.drop('text',axis=1)



X_trains,X_tests,y_train,y_test=train_test_split(X_label,y_label,test_size=0.2,random_state=0)   #change trains to train for one hot
X_tests

In [ ]:
vect=TfidfVectorizer(stop_words='english')
X_train=vect.fit_transform(X_trains)
X_test=vect.transform(X_tests)



# y_train_b=y_train['category_business']
# y_train_e=y_train['category_entertainment']
# y_train_p=y_train['category_politics']
# y_train_s=y_train['category_sport']
# y_train_t=y_train['category_tech']                                    #use this if u do one hot encoding for Y label

# y_test_b=y_test['category_business']
# y_test_e=y_test['category_entertainment']
# y_test_p=y_test['category_politics']
# y_test_s=y_test['category_sport']
# y_test_t=y_test['category_tech']

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train,y_train)
# model_b=MultinomialNB()
# model_e=MultinomialNB()
# model_p=MultinomialNB()
# model_s=MultinomialNB()
# model_t=MultinomialNB()

# model_b.fit(X_trains,y_train_b)                                               #one hot encoding code
# model_e.fit(X_trains,y_train_e)
# model_p.fit(X_trains,y_train_p)
# model_s.fit(X_trains,y_train_s)
# model_t.fit(X_trains,y_train_t)

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

MultinomialNB()

In [ ]:

print("model Train score :",model.score(X_train,y_train))
print("model test score :",model.score(X_test,y_test))



# print("train score buisness :",model_b.score(X_trains,y_train_b))
# print("test score buisness :",model_b.score(X_tests,y_test_b))
# print(" ------------------------------")
# print("train score entertainment :",model_e.score(X_trains,y_train_e))
# print("test score entertainment :",model_e.score(X_tests,y_test_e))
# print(" ------------------------------")
# print("train score politics :",model_p.score(X_trains,y_train_p))
# print("test score politics :",model_p.score(X_tests,y_test_p))
# print(" ------------------------------")
# print("train score sports :",model_s.score(X_trains,y_train_s))
# print("test score sports :",model_s.score(X_tests,y_test_s))
# print(" ------------------------------")
# print("train score tech :",model_t.score(X_trains,y_train_t))
# print("test score tech :",model_t.score(X_tests,y_test_t))
# print(" ------------------------------")

model Train score : 0.9876404494382023
model test score : 0.9752808988764045

In [ ]:
text2={'Tech giant Google on Monday announced to invite applications for the seventh batch of its startup accelerator programme in India that aims to nurture startups looking to leverage the potential of Artificial Intelligence (AI) and Machine Learning (ML).'}
X_pred=vect.transform(text2)


pred=model.predict(X_pred)[0]
if pred == 0: print('Predicted : Buisness Headline')
elif pred == 1 : print('Predicted : Entertainment')
elif pred == 2: print('Predicted : Politics Headline')
elif pred == 3: print('Predicted : Sports Headline')
elif pred == 4: print('Predicted : Tech Headline')
else: print('Unable to predict , i havnt trained on such data ')




# pred=[model_b.predict(X_pred),model_e.predict(X_pred),model_p.predict(X_pred),model_s.predict(X_pred),model_t.predict(X_pred)]

# if pred[0][0] == 1: print('Predicted : Buisness Headline')
# elif pred[1][0] == 1: print('Predicted : Entertainment')
# elif pred[2][0] == 1: print('Predicted : Politics Headline')
# elif pred[3][0] == 1: print('Predicted : Sports Headline')
# elif pred[4][0] == 1: print('Predicted : Tech Headline')
# else: print('Unable to predict , i havnt trained on such data ')

Predicted : Tech Headline